[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate --no-input && python manage.py collectstatic --no-input && gunicorn socialnetworking.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
