# Generated by Django 4.2.13 on 2026-04-23 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfileSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("instagram_url", models.URLField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("analyzing", "Analyzing"),
                            ("matched", "Matched"),
                            ("waiting", "Waiting for Match"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_instagram_url", models.URLField(blank=True)),
                ("matched_linkedin_url", models.URLField(blank=True)),
                ("similarity_score", models.FloatField(default=0.0)),
                ("match_reasons", models.JSONField(default=list)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_to",
                        to="analyzer.profilesubmission",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="analyzer.profilesubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instagram_username", models.CharField(max_length=100)),
                ("followers", models.IntegerField(default=0)),
                ("following", models.IntegerField(default=0)),
                ("post_count", models.IntegerField(default=0)),
                ("bio", models.TextField(blank=True)),
                ("hashtag_categories", models.JSONField(default=dict)),
                ("top_hashtags", models.JSONField(default=list)),
                ("locations", models.JSONField(default=list)),
                ("feature_vector", models.JSONField(default=list)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="analyzer.profilesubmission",
                    ),
                ),
            ],
        ),
    ]
